// frontend/src/components/Canvas2D.tsx
import React from 'react';

export const Canvas2D: React.FC<{ floorPlan: any }> = ({ floorPlan }) => {
  if (!floorPlan) return null;

  return (
    <div className="bg-white rounded-2xl border border-slate-100 p-6 flex flex-col items-center shadow-sm">
      <div className="w-full flex justify-between items-center border-b border-slate-100 pb-3 mb-4">
        <h4 className="text-xs font-bold font-mono uppercase text-slate-800">
          Deterministic Architectural Blueprint
        </h4>
        <span className="text-xs font-mono font-bold bg-slate-900 text-white px-3 py-1 rounded-md">
          {floorPlan.floor_name}
        </span>
      </div>

      {/* This renders the exact SVG generated by your backend engine */}
      <div 
        className="w-full bg-slate-50 border border-slate-100/70 rounded-xl overflow-hidden"
        dangerouslySetInnerHTML={{ __html: floorPlan.svg_dump || '<p>Rendering Error</p>' }} 
      />

      <div className="w-full mt-4 grid grid-cols-4 gap-2 text-[10px] text-slate-500 font-mono text-center border-t border-slate-100 pt-4">
        <span>⬛ Wall</span>
        <span>🚪 Door</span>
        <span>🪟 Window</span>
        <span>📐 CAD</span>
      </div>
    </div>
  );
};